### ISSUE TITLE
Compute Service Account Needs artifactregistry.reader Role

### ISSUE THREAD

**Issue by willisc7** [mchmarny/cloudbuild-demo#12]
When following the README sequentially I received the following error in the hello pod logs after running the first CB trigger:
```
Cannot pull image 'us-west1-docker.pkg.dev/cicd-demo-375021/cloudbuild-demo/hello@sha256:77040bddb0a9c4e9160915d3162143a5d9b2f3e21ffe2582d7e3cb1f0757ff23' from the registry.
```

I was able to fix the issue but running the following command and triggering the build again:
```
gcloud projects add-iam-policy-binding PROJECT_ID \
    --member=serviceAccount:$(gcloud projects describe PROJECT_ID \
    --format="value(projectNumber)")-compute@developer.gserviceaccount.com \
    --role="roles/artifactregistry.reader"
```

**Comment by mchmarny** [comment]
That's due to the demo clusters being configured with the default GKE (GCE) service account. I'll add this for now but switch the cluster creation command to use a custom service account
